###  在nacos上的配置  ###
server:
  port: 10020
spring:
  application:
    name: service-system #服务名
  datasource:
    url: jdbc:mysql:///ymcc-system?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:cn/hxy/ymcc/mapper/*Mapper.xml
  configuration:   # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl